[package]
name = "fishsticks"
version = "0.1.1"
edition = "2018"

[features]
default = ["sdl2"]
bundled-sdl2 = ["sdl2/bundled"]

[dependencies]
cfg-if = "1.0.0"
gilrs = { version = "0.8.1", optional = true }
sdl2 = { version = "0.35.1", optional = true }
